import './global.css';
import { Inter, Poppins } from 'next/font/google'
import Footer from '@/components/footer/Footer'
import Navbar from '@/components/navbar/Navbar'

const inter = Inter({ weight: ['500'], subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='container'>

          <Navbar />
          {children}
          <Footer />

        </div>
      </body>
    </html >
  )
}
